tasks:
  - name: Install Python
    init: >
      pyenv install 3.11 -f &&
      pyenv local 3.11 &&
      gp sync-done bundle
  - name: Install dependencies
    init: gp sync-await bundle
    command: pip install -r requirements.txt
  - name: Create Docker images
    init: >
      docker build . -f pda.Dockerfile -t pda/flask &&
      gp sync-done images
  - name: Docker Compose pull
    init: gp sync-await images
    command: docker-compose pull
